# Using R from Julia

Statistical method of ANOVA (Analysis of Variance).

In [1]:
using CSV, DataFrames, RCall

In [2]:
data1 = CSV.read("../data/machine1.csv", header=false)[:,1]

20-element Array{Float64,1}:
 53.35674558144255 
 53.45887516134873 
 52.282838627926125
 52.98746570643515 
 51.993167774733486
 53.373333606198   
 55.75410538860477 
 50.279496381439365
 53.6359586914001  
 53.517705831707495
 53.70044994508253 
 54.15592592604583 
 53.55054914606446 
 52.37319589109419 
 53.4900750059897  
 52.939458524079605
 52.16761562743534 
 50.87140009591033 
 53.144919157924924
 52.09084035473537 

In [3]:
data2 = CSV.read("../data/machine2.csv", header=false)[:,1]

18-element Array{Float64,1}:
 48.232390109774904
 52.27351779520738 
 52.0720991700097  
 51.88136380400122 
 50.898600652112705
 53.13910845160147 
 50.88296218665962 
 49.807257093374794
 49.04791179434456 
 50.91491625995569 
 50.73578182751547 
 47.6154076025163  
 50.893171221589455
 52.9559389575489  
 51.90831273558151 
 52.22159828531742 
 51.60575820776536 
 49.96704470938145 

In [4]:
data3 = CSV.read("../data/machine3.csv", header=false)[:,1]

18-element Array{Float64,1}:
 48.23239011
 52.41946369
 52.65317452
 51.94534987
 51.82515337
 53.89617752
 51.66221936
 50.48398609
 49.92915962
 51.36274088
 51.49955282
 48.44932865
 51.30260914
 53.79300458
 52.14586136
 52.3045681 
 51.70942442
 50.19259501

In [6]:
function R_ANOVA(allData)

    data = vcat([ [x fill(i, length(x))] for (i, x) in 
                enumerate(allData) ]...)
    df = DataFrame(data, [:Diameter, :MachNo])
    @rput df

    R"""
    df$MachNo <- as.factor(df$MachNo)
    anova <- summary(aov( Diameter ~ MachNo, data=df))
    fVal <- anova[[1]]["F value"][[1]][1]
    pVal <- anova[[1]]["Pr(>F)"][[1]][1]
    """
    println("R ANOVA f-value: ", @rget fVal)
    println("R ANOVA p-value: ", @rget pVal)
end

R_ANOVA (generic function with 1 method)

In [7]:
R_ANOVA([data1, data2, data3])

R ANOVA f-value: 10.516968568709022
R ANOVA p-value: 0.0001423616881714023
